theme = "bogster_light"

[editor]
true-color = true
line-number = "relative"
mouse = false

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
